//Forui zinc theme file.

import 'package:forui/forui.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart forui style create [styles]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FThemeData get zincLight {
  final colors = FColors(
    brightness: Brightness.light,
    barrier: Color(0x33000000),
    background: Color(0xFFFFFFFF),
    foreground: Color(0xFF09090B),
    primary: Color(0xCC18181B),
    primaryForeground: Color(0xFFFAFAFA),
    secondary: Color(0x11000000), 
    secondaryForeground: Color(0xFF18181B),
    muted: Color(0xCCF4F4F5),
    mutedForeground: Color(0xFF71717A),
    destructive: Color(0xCCE57373),
    destructiveForeground: Color(0xFFFFFFFF),
    error: Color(0xCCE57373),
    errorForeground: Color(0xFFFAFAFA),
    border: Color(0x66E4E4E7),
    systemOverlayStyle: SystemUiOverlayStyle.light,
  );

  final typography = _typography(colors: colors);
  final style = _style(colors: colors, typography: typography);

  return FThemeData(colors: colors, typography: typography, style: style);
}


FThemeData get zincDark {
  final colors = FColors(
    brightness: Brightness.dark,
    barrier: Color(0x55000000), // 屏障颜色更柔和
    background: Color(0xFF121212),
    foreground: Color(0xDDFFFFFF), // 白 0.87 -> 稍微浅一点
    primary: Color(0xCCFFFFFF),    // 白 0.8
    primaryForeground: Color(0xFF000000),
    secondary: Color(0x66FFFFFF),  // secondary 白 0.6 -> 再浅 (0.4)
    secondaryForeground: Color.fromARGB(255, 255, 255, 255),
    muted: Color(0xFF2C2C2E),      // 比原来柔和点
    mutedForeground: Color(0xFFFFFFFF),
    destructive: Color(0xFFB56565), // 红色淡化 (原 7F1D1D -> 柔和暗红)
    destructiveForeground: Color(0xFFFFFFFF),
    error: Color(0xFFB56565),
    errorForeground: Color(0xFF525252), 
    border: Color(0x1AFFFFFF), // Divider 白 0.12 -> 更淡 (0.1)
    systemOverlayStyle: SystemUiOverlayStyle.dark,
  );

  final typography = _typography(colors: colors);
  final style = _style(colors: colors, typography: typography);

  return FThemeData(colors: colors, typography: typography, style: style);
}


FTypography _typography({
  required FColors colors,
  String defaultFontFamily = 'PingFangSuper',
}) => FTypography(
  xs: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 12,
    height: 1,
    decoration: TextDecoration.none,
  ),
  sm: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 14,
    height: 1.25,
    decoration: TextDecoration.none,
  ),
  base: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 16,
    height: 1.5,
    decoration: TextDecoration.none,
  ),
  lg: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 18,
    height: 1.75,
    decoration: TextDecoration.none,
  ),
  xl: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 20,
    height: 1.75,
    decoration: TextDecoration.none,
  ),
  xl2: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 22,
    height: 2,
    decoration: TextDecoration.none,
  ),
  xl3: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 30,
    height: 2.25,
    decoration: TextDecoration.none,
  ),
  xl4: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 36,
    height: 2.5,
    decoration: TextDecoration.none,
  ),
  xl5: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 48,
    height: 1,
    decoration: TextDecoration.none,
  ),
  xl6: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 60,
    height: 1,
    decoration: TextDecoration.none,
  ),
  xl7: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 72,
    height: 1,
    decoration: TextDecoration.none,
  ),
  xl8: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 96,
    height: 1,
    decoration: TextDecoration.none,
  ),
);

FStyle _style({required FColors colors, required FTypography typography}) =>
    FStyle(
      formFieldStyle: FFormFieldStyle.inherit(
        colors: colors,
        typography: typography,
      ),
      focusedOutlineStyle: FFocusedOutlineStyle(
        color: colors.primary,
        borderRadius: const BorderRadius.all(Radius.circular(8)),
      ),
      iconStyle: IconThemeData(color: colors.primary, size: 20),
      tappableStyle: FTappableStyle(),
      borderRadius: const FLerpBorderRadius.all(Radius.circular(8), min: 24),
      borderWidth: 1,
      pagePadding: const EdgeInsets.symmetric(vertical: 8, horizontal: 12),
      shadow: const [
        BoxShadow(
          color: Color(0x0d000000),
          offset: Offset(0, 1),
          blurRadius: 2,
        ),
      ],
    );
