name: dext
description: "问卷调查应用"
# 以下行防止包意外发布到 pub.dev 使用 `flutter pub publish`。对于私有包，建议保留此行。
publish_to: 'none' # 如果您希望发布到 pub.dev，请移除此行
version: 1.0.2+1

environment:
  sdk: ^3.7.2

# 依赖项指定了您的包在工作时需要的其他包。
# 考虑运行 `flutter pub upgrade --major-versions` 以自动将包依赖项升级到最新版本。
# 手动更新依赖项可以通过将版本号更改为 pub.dev 上的最新版本。
# 运行 `flutter pub outdated` 可以查看哪些依赖项有可用的新版本。
dependencies:
  basic_utils: ^5.8.2
  crypto: ^3.0.6
  fast_rsa: ^3.8.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0-beta.4
  forui: ^0.12.0
  http: ^1.1.0
  dio: ^5.9.0
  layout: ^1.0.5
  window_manager: ^0.5.1
  tray_manager:
    git:
      url: https://github.com/ChuiShui233/tray_manager.git
      ref: win_fix
      path: packages/tray_manager
  url_launcher: ^6.2.5
  flutter_localizations:
    sdk: flutter
  file_picker: ^10.1.9 
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  video_player: ^2.10.0
  video_player_win: ^3.2.0
  radio_player: ^2.1.0
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0

  # 以下行将 Cupertino 图标字体添加到您的应用程序中。
  # 使用 CupertinoIcons 类以获取 iOS 样式图标。
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.5+1
  http_parser: ^4.1.2
  app_links: ^3.5.0
  clipboard_watcher: ^0.2.0
  pointycastle: ^4.0.0
  desktop_drop: ^0.6.1
  windows_single_instance: ^1.0.1
  oauth2_client: ^4.2.0
  flutter_speed_dial: ^7.0.0
  connectivity_plus: ^7.0.0
  fl_chart: ^0.69.0
  package_info_plus: ^8.0.0
  crop_image_plus:
    git:
      url: https://github.com/ChuiShui233/crop_image_plus.git
      ref: master
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 以下 "flutter_lints" 包包含一组建议的 lints 以鼓励良好的编码实践。
  # 在 `analysis_options.yaml` 文件中激活了包提供的 lint 集。
  # 查看该文件以了解如何停用特定的 lint 规则以及激活其他 lint 规则。
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    
  fonts:
    - family: PingFangSC
      fonts:
        - asset: assets/fonts/PingFangSC-Regular.otf
  
flutter_launcher_icons:
  image_path: "assets/images/Dext.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"