name: dext
description: "问卷调查"
publish_to: 'none' # 如果您希望发布到 pub.dev，请移除此行
version: 1.0.6+1020

environment:
  sdk: ^3.7.2
dependencies:
  basic_utils: ^5.8.2
  crypto: ^3.0.6
  fast_rsa: ^3.8.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0-beta.4
  forui: ^0.12.0
  http: ^1.1.0
  dio: ^5.9.0
  layout: ^1.0.5
  window_manager: ^0.5.1
  tray_manager:
    git:
      url: https://github.com/ChuiShui233/tray_manager.git
      ref: win_fix
      path: packages/tray_manager
  url_launcher: ^6.2.5
  flutter_localizations:
    sdk: flutter
  file_picker: ^10.1.9 
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  video_player: ^2.10.0
  video_player_win: ^3.2.0
  radio_player: ^2.1.0
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  syncfusion_flutter_xlsio: ^31.1.19

  # 以下行将 Cupertino 图标字体添加到您的应用程序中。
  # 使用 CupertinoIcons 类以获取 iOS 样式图标。
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.5+1
  http_parser: ^4.1.2
  image: ^4.2.0
  app_links: ^3.5.0
  clipboard_watcher: ^0.2.0
  pointycastle: ^4.0.0
  desktop_drop: ^0.6.1
  windows_single_instance: ^1.0.1
  oauth2_client: ^4.2.0
  flutter_speed_dial: ^7.0.0
  connectivity_plus: ^7.0.0
  fl_chart: 0.71.0
  package_info_plus: ^8.0.0
  crop_image_plus:
    git:
      url: https://github.com/ChuiShui233/crop_image_plus.git
      ref: master
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    
  fonts:
    - family: PingFangSuper
      fonts:
        - asset: assets/fonts/SuperPingFangV1.ttf
  
flutter_launcher_icons:
  image_path: "assets/images/Dext.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
